image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-default

stages:
  - package
  - release

.install_tools: &install_tools |
  apt update
  apt -y install wget cpio unar
  wget "$OPSIDEVTOOLS_URL_LINUX_X64" -O opsi-dev-tools.tar.gz
  tar -xvf opsi-dev-tools.tar.gz
  cp opsi-dev-tool opsi-dev-cli

package for OBS:
  stage: package
  before_script:
    - *install_tools
    - export DEBIAN_FRONTEND noninteractive
    - export DEBCONF_NONINTERACTIVE_SEEN true
    - echo "tzdata tzdata/Areas select Europe" > /tmp/preseed.txt
    - echo "tzdata tzdata/Zones/Europe select Berlin" >> /tmp/preseed.txt
    - debconf-set-selections /tmp/preseed.txt
    - DEBIAN_FRONTEND=noninteractive apt update
    - DEBIAN_FRONTEND=noninteractive apt -y install gcc fakeroot dpkg-dev debhelper autoconf
    - DEBIAN_FRONTEND=noninteractive apt -y install autotools-dev libwrap0-dev po-debconf
    - DEBIAN_FRONTEND=noninteractive apt -y install debhelper osc python3-pip
  script:
    - wget https://ftp.debian.org/debian/pool/main/t/tftp-hpa/tftp-hpa_5.2+20240610.orig.tar.gz
    - tar -xvf tftp-hpa_5.2+20240610.orig.tar.gz
    - mv tftp-hpa-5.2+20240610/* .
    - ./autogen.sh
    - ./configure
    - ./create_source.sh
    - test -f opsi-tftp-hpa_*.dsc
    - test -f opsi-tftp-hpa_*.tar.gz
    - test -f opsi-tftp-hpa.spec
    - wget "$OPSIDEVTOOLS_URL_LINUX_X64" -O opsi-dev-tools.tar.gz
    - tar -xvf opsi-dev-tools.tar.gz
    - cp opsi-dev-tool opsi-dev-cli
    - version=$(head -n1 debian/changelog | cut -d'(' -f2 | cut -d')' -f1 | cut -d'-' -f1)
    - release=$(head -n1 debian/changelog | cut -d'(' -f2 | cut -d')' -f1 | cut -d'-' -f2)
    - '[ "$CI_COMMIT_TAG" = "" ] || opsi-dev-tool  -l info --obs-replace-files https://build.opensuse.org home:uibmz:opsi:4.3:development opsi-tftp-hpa opsi-tftp-hpa_*.tar.gz opsi-tftp-hpa_*.dsc opsi-tftp-hpa.spec'
    - '[ "$CI_COMMIT_TAG" = "" ] || opsi-dev-cli -l info release-service register-package-version opsi-tftp-hpa SERVER_PACKAGE --version="$version-$release" --changelog-file=debian/changelog'
    - '[ "$CI_COMMIT_TAG" = "" ] || opsi-dev-cli -l info release-service push-repository-state opsi-tftp-hpa SERVER_PACKAGE SERVER_PACKAGE-4.3-development --version="$version-$release"'
  artifacts:
    paths:
     - opsi-tftp-hpa_*.dsc
     - opsi-tftp-hpa_*.tar.gz
     - opsi-tftp-hpa.spec
    expire_in: 2 days
