#!/bin/sh

set -e

case "$1" in
	remove)
		if [ -e /etc/default/tftpd-hpa ]
		then
		    . /etc/default/tftpd-hpa

		    for d in $TFTP_DIRECTORY
		    do
			if [ -d "$d" ]
			then
			    rmdir --ignore-fail-on-non-empty "$d" > /dev/null 2>&1 || true
			fi
		    done
		fi
		;;

	purge)
		rm -f /etc/default/tftpd-hpa
		;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		;;

	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
